"use client";
import { ArrowLeft,ArrowRight,AtSign,BriefcaseBusiness,Check,Palette,PartyPopper,Sparkles,UserRound } from "lucide-react"; import { useRouter } from "next/navigation"; import { useEffect,useState } from "react"; import { Logo } from "./logo";
const steps=["Account type","Username","About you","Socials","First links","Theme","Preview","Publish"];
export function Onboarding(){const router=useRouter();const [step,setStep]=useState(0),[username,setUsername]=useState("safar"),[selected,setSelected]=useState("Creator");useEffect(()=>{localStorage.setItem("linkme-onboarding-step",String(step))},[step]);function next(){if(step===7)router.push("/dashboard/overview");else setStep(step+1)}
return <main className="onboarding-page"><header><Logo/><span>Step {step+1} of 8</span></header><div className="progress"><i style={{width:`${(step+1)*12.5}%`}}/></div><section className="onboarding-card"><span className="step-icon">{step===7?<PartyPopper/>:step===5?<Palette/>:step===1?<AtSign/>:<Sparkles/>}</span><h1>{["How will you use Linkme?","Claim your corner of the internet","Tell people a little about you","Where can people find you?","Add your first links","Choose your starting style","Everything looks great","Your Linkme is ready"][step]}</h1><p>{["We'll tailor your experience around what you do.","Choose something memorable. You can change it later.","A warm introduction helps visitors connect.","Add the places where you're already active.","Give visitors somewhere meaningful to go.","Pick a mood - we'll make it yours.","Take one last look before publishing.","Your new digital home is ready to share."][step]}</p><div className="step-content">
{step===0&&<div className="account-options">{[["Creator",UserRound],["Business",BriefcaseBusiness],["Personal",UserRound]].map(([n,I])=>{const Icon=I as typeof UserRound;return <button key={n as string} className={selected===n?"selected":""} onClick={()=>setSelected(n as string)}><Icon/><b>{n as string}</b><small>{n==="Creator"?"Build an audience":n==="Business"?"Grow your brand":"Share your world"}</small>{selected===n&&<Check/>}</button>})}</div>}
{step===1&&<label className="username-input"><span>linkme.com/</span><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))}/><Check/><small>{username.length>2?"Available - great choice!":"Use at least 3 characters"}</small></label>}
{step===2&&<div className="form-stack"><label>Display name<input defaultValue="Safar Noor"/></label><label>Short bio<textarea defaultValue="Creative director and product thinker building more human corners of the internet."/></label></div>}
{step===3&&<div className="social-select">{["Instagram","YouTube","LinkedIn","TikTok","Spotify","GitHub","Other"].map((x,i)=><button className={i<3?"selected":""} key={x}>{x}{i<3&&<Check/>}</button>)}</div>}
{step===4&&<div className="form-stack"><label>Link title<input defaultValue="My latest work"/></label><label>Destination URL<input defaultValue="https://example.com"/></label><button className="add-another">+ Add another link</button></div>}
{step===5&&<div className="theme-select">{["Aurora","Studio","Night","Sunset"].map((x,i)=><button className={i===0?"selected":""} key={x}><i className={`theme-swatch s${i}`}/><b>{x}</b>{i===0&&<Check/>}</button>)}</div>}
{step===6&&<div className="mini-preview"><div className="fake-avatar"/><b>Safar Noor</b><p>@{username}</p><i/><i/><i/></div>}
{step===7&&<div className="publish-box"><span>https://linkme.com/{username}</span><button onClick={()=>navigator.clipboard?.writeText(`https://linkme.com/${username}`)}>Copy link</button></div>}
</div><div className="onboarding-actions"><button className="btn back" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft/> Back</button><button className="btn primary" onClick={next} disabled={step===1&&username.length<3}>{step===7?"Go to dashboard":"Continue"}<ArrowRight/></button></div></section><footer>{steps.map((x,i)=><span key={x} className={i===step?"current":i<step?"done":""}>{i<step?<Check/>:i+1}<b>{x}</b></span>)}</footer></main>}
