"use client";
import { useMemo,useState } from "react"; import { BadgeCheck,BookOpen,CalendarDays,Camera,ChevronRight,Clapperboard,Copy,Globe2,Mail,MapPin,MoreHorizontal,Music2,Search,Share2,Sparkles } from "lucide-react"; import { initialLinks,profile } from "@/lib/mock";
const icons={book:BookOpen,sparkles:Sparkles,mail:Mail,calendar:CalendarDays};
export function ProfilePreview({embedded=false}:{embedded?:boolean}){
 const [query,setQuery]=useState(""),[followed,setFollowed]=useState(false),[toast,setToast]=useState(""); const links=useMemo(()=>initialLinks.filter(x=>(x.title+x.description).toLowerCase().includes(query.toLowerCase())),[query]);
 function notice(t:string){setToast(t);setTimeout(()=>setToast(""),1800)}
 return <div className={embedded?"profile-page embedded":"profile-page"}><div className="profile-orb one"/><div className="profile-orb two"/><main className="profile-card-wrap"><div className="profile-toolbar"><span className="mini-brand"><span className="logo-mark mini">L</span> linkme</span><div><button className="circle-btn" aria-label="Copy profile link" onClick={()=>{navigator.clipboard?.writeText(location.href);notice("Profile link copied")}}><Copy size={16}/></button><button className="circle-btn" aria-label="Share profile" onClick={()=>notice("Share menu ready")}><Share2 size={16}/></button><button className="circle-btn" aria-label="More options"><MoreHorizontal size={17}/></button></div></div>
 <div className="avatar"><span>SN</span><span className="status-dot"/></div><div className="profile-name"><h1>{profile.name}</h1><BadgeCheck size={20} className="verified"/></div><div className="username">linkme.com/{profile.username}</div><p className="bio">{profile.bio}</p><div className="location"><MapPin size={14}/>{profile.location}</div><div className="profile-actions"><button className="btn profile-follow" onClick={()=>setFollowed(!followed)}>{followed?"Following":"Follow"}</button><button className="btn profile-contact" onClick={()=>notice("Message composer opened")}><Mail size={16}/> Contact</button></div><div className="socials"><a href="https://instagram.com" aria-label="Instagram"><Camera/></a><a href="https://youtube.com" aria-label="YouTube"><Clapperboard/></a><a href="https://spotify.com" aria-label="Spotify"><Music2/></a><a href="https://example.com" aria-label="Website"><Globe2/></a></div>
 <label className="profile-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Safar's links" aria-label="Search profile links"/></label><div className="profile-links">{links.map(item=>{const Icon=icons[item.icon as keyof typeof icons]||Globe2;return <a className={`profile-link ${item.badge==="Featured"?"featured":""}`} href={item.url} key={item.id} target="_blank" rel="noreferrer"><span className="link-icon"><Icon size={20}/></span><span><strong>{item.title}</strong><small>{item.description}</small></span>{item.badge&&<em>{item.badge}</em>}<ChevronRight className="arrow" size={18}/></a>})}{links.length===0&&<div className="empty">No links match “{query}”.</div>}</div>
 <section className="newsletter"><span className="eyebrow">THE SUNDAY EDIT</span><h2>Good ideas, delivered slowly.</h2><p>A thoughtful note on design and living, every other Sunday.</p><form onSubmit={e=>{e.preventDefault();notice("You're on the list ✨")}}><input required type="email" placeholder="you@email.com" aria-label="Email address"/><button>Join</button></form></section><footer className="profile-footer"><span className="logo-mark mini">L</span> Made with Linkme</footer></main>{toast&&<div className="toast" role="status">{toast}</div>}</div>
}
